jenkins_admin_username: admin

jenkins_admin_password: my_secret_pass_from_vault

jenkins_admin_password_file: ""

jenkins_connection_delay: 5

jenkins_connection_retries: 60

jenkins_home: /var/lib/jenkins

jenkins_hostname: localhost

jenkins_http_port: 8080

jenkins_init_file: /etc/sysconfig/jenkins

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "JENKINS_JAVA_OPTIONS"
    value: "{{ jenkins_java_options }}"

# Required if you use Jenkins CLI only
# jenkins_jar_location: /opt/jenkins-cli.jar

# Disable CSRF so jenkins_job plugin can work properly
jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"

jenkins_job_name: "devops_demoapp_pipeline"

jenkins_plugin_timeout: 30

jenkins_plugin_updates_expiration: 86400

jenkins_plugins: 
  - name: git
    # version: "4.10.3"
  - name: workflow-aggregator
    # version: "2.6"
  - name: pipeline-aws
    # version: "1.43"

jenkins_plugins_install_dependencies: true

jenkins_plugins_state: present

jenkins_process_user: jenkins

jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_updates_url: "https://updates.jenkins.io"

jenkins_url_prefix: ""